fix streetcode card
ita-social-projects/StreetCode_Client pull request #1136
Opened 2024-01-24 13:12 UTC by BohdanBybliv

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-01-28 22:45 UTC, KateYatsiuk requested changes
1) Is it ok that according to the mockup the button is long on tablets (screenshot below) and in your pr it has the same length as on the desktop version?
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/4fbc8079-6ac3-4de5-bf7e-811ba718e26d)

2) I don't get it, in the ticket description it is stated like that: 
> "**From 360 px till 767px** the streetcodecard component (The ʼПрослухати текстʼ button) is displayed as on a mobile version"

That's what we have:
766 - ok
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/a535661b-8023-4a23-94f6-54fcecf5b432)
**767 - seems not ok, why tablet? It should be the same as in 766, shouldn't it?**
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/152f74fd-0739-4017-9418-82ab93bfc2bc)
768 - ok
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/3e24bdca-d3ef-44b6-9cef-1cf7705ca333)

2024-02-02 14:18 UTC, BohdanBybliv commented
> 1. Is it ok that according to the mockup the button is long on tablets (screenshot below) and in your pr it has the same length as on the desktop version?
>    ![image](https://private-user-images.githubusercontent.com/113370393/300298917-4fbc8079-6ac3-4de5-bf7e-811ba718e26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODMzNjcsIm5iZiI6MTcwNjg4MzA2NywicGF0aCI6Ii8xMTMzNzAzOTMvMzAwMjk4OTE3LTRmYmM4MDc5LTZhYzMtNGRlNS1iZjdlLTgxMWJhNzE4ZTI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNDExMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTYwNzI1ZDdlZDQ2YjRjZTY1NTU4NGU3YTAzZmMxNTdiNDdjOWExOWRlYjQ4YzIwY2ExMjY5MTI2MmE2OTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nj_tKmH12SviQdfyohKSZ-V1bhD7bbcD8Cx2P3yMmGc)
> 2. I don't get it, in the ticket description it is stated like that:
> 
> > "**From 360 px till 767px** the streetcodecard component (The ʼПрослухати текстʼ button) is displayed as on a mobile version"
> 
> That's what we have: 766 - ok ![image](https://private-user-images.githubusercontent.com/113370393/300298740-a535661b-8023-4a23-94f6-54fcecf5b432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODMzNjcsIm5iZiI6MTcwNjg4MzA2NywicGF0aCI6Ii8xMTMzNzAzOTMvMzAwMjk4NzQwLWE1MzU2NjFiLTgwMjMtNGEyMy05NGY2LTU0ZmNlY2Y1YjQzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNDExMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTRhMTg5YTY1ODgzZjU3MWFiYzFlOWY0MGMyNDNkMWNkNjZmMTRlMWQ1MTI3MWNmMmQ4NmRkNmRmZjZmMTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B0673cYQaA4OOBl-cK-JKeM4r7fEgyOeJArMW7oFYBA) **767 - seems not ok, why tablet? It should be the same as in 766, shouldn't it?** ![image](https://private-user-images.githubusercontent.com/113370393/300298736-152f74fd-0739-4017-9418-82ab93bfc2bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODMzNjcsIm5iZiI6MTcwNjg4MzA2NywicGF0aCI6Ii8xMTMzNzAzOTMvMzAwMjk4NzM2LTE1MmY3NGZkLTA3MzktNDAxNy05NDE4LTgyYWI5M2JmYzJiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNDExMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTIwMjc5Y2FkM2M1ZWMwNWNiODNiY2UwYTY4Njc4ZTkzMjM4YjJjMDkzNTUyNTk5MmZkZWI3MjE3YzBkYTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_YWdtYmwU_RkODHo4x4Jy3-1UfLiwpG6GXMyz75g9M) 768 - ok ![image](https://private-user-images.githubusercontent.com/113370393/300298745-3e24bdca-d3ef-44b6-9cef-1cf7705ca333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODMzNjcsIm5iZiI6MTcwNjg4MzA2NywicGF0aCI6Ii8xMTMzNzAzOTMvMzAwMjk4NzQ1LTNlMjRiZGNhLWQzZWYtNDRiNi05Y2VmLTFjZjc3MDVjYTMzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNDExMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjRmZGQ0MzUyZGQ2Yjk3YjllNDdiYjY0NzlmZTE5ODE1MTc1MzI4OTMwOWEyN2VhMTQzMDg0ZDM2MzQzOThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XIIuxNFSW2NpiPrAhK03G46IVuNnIU2qcX8g4hF0xfU)

2024-02-02 14:23 UTC, BohdanBybliv commented
It works correctly. Сhange the scale to 100% in the device settings and try again.
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/125794488/9b3c3eca-3a9f-48b0-8f12-7a301cd18721)

2024-02-11 13:53 UTC, IvannYad approved these changes

2024-02-11 18:39 UTC, mykola-krai approved these changes

2024-02-12 15:49 UTC, Adeodonne approved these changes

2024-02-12 17:56 UTC, KateYatsiuk approved these changes

2024-02-20 15:29 UTC, merged