Feature/issue 1154
ita-social-projects/StreetCode_Client pull request #1195
Opened 2024-03-16 20:38 UTC by Spoilsport0

## Summary of issue
[Streetcode/Зв’язки історії][From Customer][CO #7] When hovering over the card, the next block "Для фанатів" should not move down

ToDo
- it was added a line height: 535px for block "Зв'язки історії" 
- it was added margin-top for block  "Для фанатів"

2024-03-18 16:55 UTC, yaakymiv approved these changes

2024-03-22 07:39 UTC, Lazy-Lenny requested changes

2024-03-22 07:39 UTC, Lazy-Lenny commented on src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
Add new line to the end of file

2024-03-22 07:39 UTC, Lazy-Lenny commented on src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Add new line to the end of file

2024-03-22 07:43 UTC, Lazy-Lenny approved these changes

2024-03-24 11:48 UTC, vasylashka approved these changes

2024-03-27 08:01 UTC, merged