Layout/qr component
ita-social-projects/StreetCode_Client pull request #12
Opened 2022-12-30 15:04 UTC by PingvinAustr

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-12-30 15:09 UTC, EyR1oN approved these changes

2022-12-30 15:55 UTC, AleXLaeR requested changes

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    width:326px/822px;
Width p-ty does not have such syntax; Maybe a typo?

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.flexed(row,center,center);
Consider using **flex-centered** mixin here.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.rem-padded(134px, 0, 0, 0)
You don't need to specify all parameter values; they are already defaulted to 0.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.flexed(column,center,flex-start);
Please fix the spacing.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.rem-padded(0,0,0,31px);
You can just specify $left: 31px here, as all other parameter values are already defaulted to 0.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.flexed(column, center, center);
Consider rewriting **flex-centered** mixin where it accepts a **direction** which can be defaulted to **row**, making it more flexible and better suitable for the latter.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.font-faced(fonts.$roboto-font, normal, 500, 24px);
Roboto font is default value.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.font-faced(fonts.$roboto-font, normal, 200, 20px);
Roboto font is default value.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.rem-margined(2px,0,0,0);
The same as above.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.rem-margined(22px,0,0,0);
The same as above.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.rem-padded(0,0,0,14px);
The same as above.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    .p_bold {
Non-consistent class names; Consider writing all of them in camelCase.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +.QRBlockTextWrapper{
Please fix the spacing.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.styles.scss
> +    img{
Please fix the spacing.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/QRBlock/QR.component.tsx
> +let QR = require("../../assets/images/QR.png");
- fix relative paths hell on imports;
- why use require instead of basic named import?;

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/InterestingFacts/InterestingFacts.styles.scss
> +    }
- Spacing;
- Pixels aren't converted to Rems;

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/InterestingFacts/InterestingFacts.styles.scss
> +.heightContainer{
Spacing.

2022-12-30 15:55 UTC, AleXLaeR commented on src/components/InterestingFacts/InterestingFacts.styles.scss
> +    height: pxToRem(660px);
Consider moving width & height combination to a separate mixin, smth like **sized**:

@mixin sized($width, $height) {
  width: pxToRem($width) !important;
  height: pxToRem($height) !important;
}

Also, make **parent-sized** mixin dependant on the abovementioned one.

2022-12-30 20:09 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    width:326px/822px;
Fixed

2022-12-30 20:10 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.flexed(row,center,center);
Agree. Done

2022-12-30 20:11 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.rem-padded(134px, 0, 0, 0)
Agree. Done

2022-12-30 20:12 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.flexed(column,center,flex-start);
Agree. Done

2022-12-30 20:12 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.rem-padded(0,0,0,31px);
Agree. Done

2022-12-30 20:14 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    @include mut.flexed(column, center, center);
Agree. Done

2022-12-30 20:15 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.font-faced(fonts.$roboto-font, normal, 500, 24px);
Yes, it is. But it is shorter to write it here than to remove font family from line 44 and specify names of all other parameters

2022-12-30 20:16 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.font-faced(fonts.$roboto-font, normal, 200, 20px);
Yes, it is. But it is shorter to write it here than to remove font family from line 44 and specify names of all other parameters

2022-12-30 20:16 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.rem-margined(2px,0,0,0);
Agree. Done

2022-12-30 20:17 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.rem-margined(22px,0,0,0);
Agree. Done

2022-12-30 20:17 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +        @include mut.rem-padded(0,0,0,14px);
Agree. Done

2022-12-30 20:20 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    .p_bold {
Agree. Done

2022-12-30 20:22 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +.QRBlockTextWrapper{
Spacing is ok now

2022-12-30 20:22 UTC, PingvinAustr commented on src/components/QRBlock/QR.styles.scss
> +    img{
Spacing is ok now

2022-12-30 20:25 UTC, PingvinAustr commented on src/components/QRBlock/QR.component.tsx
> +let QR = require("../../assets/images/QR.png");
1. Changed
2. I do not think that it is a big deal

2022-12-30 20:26 UTC, PingvinAustr commented on src/components/InterestingFacts/InterestingFacts.styles.scss
> +    }
Done

2022-12-30 20:26 UTC, PingvinAustr commented on src/components/InterestingFacts/InterestingFacts.styles.scss
> +.heightContainer{
Done

2022-12-30 20:27 UTC, PingvinAustr commented on src/components/InterestingFacts/InterestingFacts.styles.scss
> +    height: pxToRem(660px);
Good idea. I'll consider this later

2022-12-30 20:48 UTC, Tatiana2424 approved these changes

2022-12-31 08:03 UTC, AleXLaeR approved these changes

2022-12-31 08:37 UTC, merged