fixed issue-966
ita-social-projects/StreetCode_Client pull request #1210
Opened 2024-03-24 20:39 UTC by Spoilsport0

## Summary of issue
[From Customer][Для звʼязків][Catalog] The "Для звʼязків" image isn't displayed on catalog

## Summary of change

added a check if there is a picture related to the story, it is displayed, if not, it is blackandwhite image

2024-03-26 16:20 UTC, vasylashka commented on src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
> +            ImagesApi.getByStreetcodeId(id ?? 1)
It would be better not to use ImagesApi directly, but use getImageById from image-store.tsx

2024-04-01 14:34 UTC, IvannYad requested changes

2024-04-14 09:22 UTC, yaakymiv commented on src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
> +                TransactionLinksApi.getByStreetcodeId(id).then((x) => setArlink(x.url));
Just a suggestion . In 51st line you are using a promise-based approach. Since you're using async/await a bit earlier (line 37), you might want to consider using it consistently here as well.

2024-04-14 12:42 UTC, Lazy-Lenny requested changes

2024-04-14 12:42 UTC, Lazy-Lenny commented on src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
> +};
If we only need one image (as said imagesForSlider[0]), we should set imageForSlider and use Image class instead of Image[] at line 29

2024-04-14 15:35 UTC, Lazy-Lenny approved these changes

2024-04-14 15:35 UTC, Lazy-Lenny commented on src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
> +    const [imagesForSlider, setImagesForSlider] = useState<Image>(); // Change type to Image
change to [imageForSlider, setImageForSlider] = useState<Image>()

2024-04-14 16:29 UTC, vasylashka approved these changes

2024-04-21 19:00 UTC, IvannYad approved these changes

2024-04-26 05:49 UTC, merged