changed some styles
ita-social-projects/StreetCode_Client pull request #1217
Opened 2024-03-30 15:06 UTC by Spoilsport0

## Summary of issue

The breadcrumbs font doesn't match the mockup.
Font-weight 600
Line-height 18.8571px

## Summary of change

Font-weight 500
Line-height 14.06px

2024-04-01 16:23 UTC, vzabrodskyi approved these changes

2024-04-05 07:24 UTC, vasylashka approved these changes

2024-04-06 09:20 UTC, IvannYad approved these changes

2024-04-14 09:24 UTC, yaakymiv approved these changes

2024-04-14 12:46 UTC, Lazy-Lenny requested changes

2024-04-14 12:46 UTC, Lazy-Lenny commented on src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.styles.scss
Add new line at the end of file

2024-04-14 13:04 UTC, Lazy-Lenny approved these changes

2024-04-14 20:08 UTC, merged