Add alt as empty string to every image we create
ita-social-projects/StreetCode_Client pull request #1228
Opened 2024-04-16 09:43 UTC by vasylashka

Merge at the same time with [backend part](https://github.com/ita-social-projects/StreetCode/pull/1356)

2024-04-17 15:16 UTC, Lazy-Lenny requested changes

2024-04-17 15:16 UTC, Lazy-Lenny commented on src/app/common/components/FileUploader/FileUploader.component.tsx
> +                                     alt: "" };
@Spoilsport0 checks if alt is NOT empty, so i would suggest adding some kind of default value when creating image like '#' or 'default'

2024-04-17 15:19 UTC, vasylashka commented on src/app/common/components/FileUploader/FileUploader.component.tsx
> +                                     alt: "" };
Okay! I will change it to default. Thanks for suggestion.

2024-04-19 11:48 UTC, Spoilsport0 approved these changes

2024-04-21 18:51 UTC, IvannYad approved these changes

2024-04-21 18:52 UTC, merged