Search filter on Admin page fixed when filter selected and removed
ita-social-projects/StreetCode_Client pull request #1422
Opened 2024-09-18 13:08 UTC by mythter

* Ticket ita-social-projects/StreetCode#1765

## Summary of issue

After filtering streetcodes by status admin can`t go back to the whole list of Streetcodes neither deleting data in 'Статус стріткодів' field nor clicking on 'Стріткоди' tub. The only way go back to the whole list is to choose different from 'Стріткоди' tub (e.g 'Партнери', 'Едітор') and then click on 'Стріткоди' tub

## Summary of change

Now admin can remove status filter and search will work properly

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-09-29 22:12 UTC, sashapanasiuk5 requested changes
I cant go back to the whole list of streetcode by clicking on 'Streetcode' tab

2024-09-30 06:34 UTC, mythter commented
> I cant go back to the whole list of streetcode by clicking on 'Streetcode' tab

Yes, this is another issue that was fixed it in this [PR](https://github.com/ita-social-projects/StreetCode_Client/pull/1399)

2024-09-30 08:58 UTC, ulyasaur approved these changes

2024-09-30 09:39 UTC, sashapanasiuk5 approved these changes

2024-09-30 11:51 UTC, merged