changed стріткод to historycode
ita-social-projects/StreetCode_Client pull request #1488
Opened 2024-12-27 18:10 UTC by lisaaksionova

dev
## GitHub

* [Main GitHub ticket](https://github.com/ita-social-projects/StreetCode/issues/1847)

## Summary of issue

Стріткод has to be changed to Historycode

## Summary of change

Changed every mention of стріткод to historycode

2024-12-27 18:15 UTC, YuliiaAndreieva approved these changes

2024-12-27 18:20 UTC, YaroslavRosnovskyi approved these changes

2024-12-28 11:55 UTC, darkravchuk commented on src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx
> +import InputPanel from './components/nent';
Incorrect import path: './components/nent' seems wrong. Please double-check the file structure to ensure the correct component is being imported.

2024-12-28 11:59 UTC, darkravchuk requested changes
Please double-check the file structure to ensure the correct component is being imported.

2024-12-28 15:39 UTC, closed without merging