sources adaptives
ita-social-projects/StreetCode_Client pull request #168
Opened 2023-04-12 14:38 UTC by Chynchenko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-04-13 06:51 UTC, Katerix requested changes

2023-04-13 06:51 UTC, Katerix commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +    @include mut.positioned-as(absolute, $left: 90%, $top: -15px);
overriding lib classes like .ant-modal-close like this you ovverride all this components in project. Don't do it again please.

2023-04-13 06:51 UTC, Katerix commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +      display: flex;
same

2023-04-13 06:51 UTC, Katerix commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +  height: 370px;
remove space between classes on line 115

2023-04-13 06:51 UTC, Katerix commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +  width: 340px;
it is a better practice to use more specific selecctors

2023-04-25 08:40 UTC, Chynchenko commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +    @include mut.positioned-as(absolute, $left: 90%, $top: -15px);
I'll take it

2023-04-25 08:41 UTC, Chynchenko commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +      display: flex;
+

2023-04-25 08:41 UTC, Chynchenko commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +  height: 370px;
ok)

2023-04-25 08:41 UTC, Chynchenko commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +  width: 340px;
ok)

2023-04-25 08:43 UTC, merged