Created store, Front admin for fans and made slider on streetcode pag…
ita-social-projects/StreetCode_Client pull request #258
Opened 2023-05-08 18:24 UTC by DanyilTerentiev

…e for fans

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions
#257

2023-05-08 18:28 UTC, Katerix commented on src/features/AdminPage/ForFansPage/ForFansMainPage.style.scss
> +.ForFansPageContainer {
classes are commonly named from a small letter

2023-05-08 18:29 UTC, Katerix requested changes

2023-05-08 18:29 UTC, Katerix commented on src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
> +
big comment

2023-05-08 19:39 UTC, NadiaKishchuk commented on src/app/common/components/modals/Sources/SourcesModal.component.tsx
> +              && (
Do you really need this comparison?

2023-05-08 19:42 UTC, NadiaKishchuk commented on src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
> +    };
you can also use the confirmation modal which is in our common modals. But it is not necessary, just a little improvement.

2023-05-08 19:44 UTC, NadiaKishchuk reviewed
please, fix our comments

2023-05-09 10:16 UTC, Tysyatsky reviewed
Great work overall. Left some comments for minor improvements.

2023-05-09 10:16 UTC, Tysyatsky commented on src/app/common/components/modals/Sources/SourcesModal.component.tsx
> +        </>
you can refactor this piece of code a little. Just use ternary operator, because this two conditions are opposite.

2023-05-09 10:16 UTC, Tysyatsky commented on src/app/common/components/modals/Sources/SourcesModal.styles.scss
> +    font-size: 15px;
here you can use with font mixin.

2023-05-09 10:16 UTC, Tysyatsky commented on src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
> +    const [isModalDeleteVisible, setIsModalDeleteVisible] = useState(false);
A small piece of advice: you could use a modalstore for signalizing the open/close state for modals.

2023-05-10 20:42 UTC, DanyilTerentiev commented on src/features/AdminPage/ForFansPage/ForFansMainPage.component.tsx
> +import PageBar from '../PageBar/PageBar.component';
It is, but what does it mean?)

2023-05-10 20:42 UTC, DanyilTerentiev commented on src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
> +    const [isModalDeleteVisible, setIsModalDeleteVisible] = useState(false);
Gonna know in the next admin task, but I don't want to change it here if it is not critical)

2023-05-10 20:44 UTC, DanyilTerentiev commented on src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
> +    //        .sourcesContainer {
Done!

2023-05-10 20:45 UTC, DanyilTerentiev commented on src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
> +    };
Gonna do it the next modal if it is not so necessary)

2023-05-10 20:45 UTC, DanyilTerentiev commented on src/app/common/components/modals/Sources/SourcesModal.component.tsx
> +        </>
Done already, thank you for the tip!

2023-05-10 20:51 UTC, DanyilTerentiev commented on src/app/common/components/modals/Sources/SourcesModal.component.tsx
> +              && (
Already fixed

2023-05-10 20:51 UTC, DanyilTerentiev commented on src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
> +
Deleted already

2023-05-11 10:55 UTC, Katerix reviewed
Goog job! keep in mind that we have mixins which are good to use :)

2023-05-11 10:55 UTC, Katerix commented on src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss
> +  }
u can use mixin SizedImportant()

2023-05-11 11:31 UTC, DanyilTerentiev commented on src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss
> +  }
Done!

2023-05-11 11:31 UTC, Katerix approved these changes

2023-05-11 11:35 UTC, merged