Addition-text-blok-with-inner-developers-reference
ita-social-projects/StreetCode_Client pull request #273
Opened 2023-05-15 09:14 UTC by ValDekh

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-05-15 09:31 UTC, ormykhalyshyn requested changes
small fixes, but overall good job)

2023-05-15 09:31 UTC, ormykhalyshyn commented on src/app/router/Routes.tsx
You need to fix this.
All admin components must be protected, and the code must be without such comments.

2023-05-15 09:31 UTC, ormykhalyshyn commented on src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Change this import TimelineApi from '../../../app/api/timeline/timeline.api';
To like this import TimelineItem from '@/models/timeline/chronology.model';

2023-05-15 09:31 UTC, ormykhalyshyn commented on src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx
change syntaxis for import

2023-05-15 09:31 UTC, ormykhalyshyn commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextForm.component.tsx
same import

2023-05-15 09:31 UTC, ormykhalyshyn commented on src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
delete comments

2023-05-15 21:51 UTC, ValDekh commented on src/app/router/Routes.tsx
Done

2023-05-15 21:59 UTC, ValDekh commented on src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
Done

2023-05-15 22:01 UTC, ValDekh commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
done

2023-05-15 22:03 UTC, ValDekh commented on src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx
this imports work correct, I hadn't changed it previously

2023-05-15 22:04 UTC, ValDekh commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
done

2023-05-15 22:11 UTC, ValDekh commented on src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx
Done

2023-05-15 22:11 UTC, ValDekh commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextForm.component.tsx
Done

2023-05-15 22:15 UTC, ValDekh commented on src/features/StreetcodePage/Streetcode.component.tsx
done

2023-05-15 22:16 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
Done

2023-05-15 22:18 UTC, ValDekh commented on src/models/streetcode/text-contents.model.ts
Done

2023-05-15 22:19 UTC, ValDekh commented on src/models/streetcode/streetcode-types.model.ts
Done

2023-05-17 06:25 UTC, NadiaKishchuk approved these changes

2023-05-17 09:17 UTC, Dobriyr requested changes
great work, but there is a note about the code style

2023-05-17 09:17 UTC, Dobriyr commented on src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
> -                    {/* <StreetCodeBlock /> */}
this comment should be left, we need to remember about this block in the future

2023-05-17 09:17 UTC, Dobriyr commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
> +/* eslint-disable react/jsx-props-no-multi-spaces */
missed comment

2023-05-17 09:17 UTC, Dobriyr commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
> +/* eslint-disable react/jsx-props-no-multi-spaces */
1 more

2023-05-17 09:17 UTC, Dobriyr commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
> +            <div className="display-flex-row">
the style of the code is scattered
it is worth using the same quotation marks for all strings

2023-05-17 09:17 UTC, Dobriyr commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
> +                    className="streetcode-custom-button button-margin-vertical button-margin-right"
same here

2023-05-17 09:17 UTC, Dobriyr commented on src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
> +                    className="streetcode-custom-button button-margin-vertical"
and here)

2023-05-17 09:17 UTC, Dobriyr commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +            color: #891F16;
should use or create color from our assets

2023-05-22 17:08 UTC, closed without merging