News admin page danya
ita-social-projects/StreetCode_Client pull request #290
Opened 2023-05-18 07:55 UTC by DanyilTerentiev

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)
#289 

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-05-18 08:54 UTC, ormykhalyshyn requested changes

2023-05-18 08:54 UTC, ormykhalyshyn commented on src/app/router/Routes.tsx
Return Protected Component

2023-05-18 08:54 UTC, ormykhalyshyn commented on src/features/AdditionalPages/NewsPage/News.component.tsx
consol.logs, comments

2023-05-18 08:54 UTC, ormykhalyshyn commented on src/features/AdditionalPages/NewsPage/Title/Title.component.tsx
...

2023-05-18 09:05 UTC, Katerix requested changes
Good job! Please read my comments below and be attentive to code styling! You are a smartass ))

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersBlock/PartnersBlock.styles.scss
> +        .keyPartnersBlock{
spaces

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersBlock/PartnersBlock.styles.scss
> +
maybe some mixins here?

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersBlock/PartnersBlock.styles.scss
> +            margin-bottom: f.pxToRem(80px);
and here

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersBlock/PartnersBlock.styles.scss
> +            .partnersItem{
space

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersBlock/PartnersBlock.styles.scss
> +            display: flex;
here

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersBlock/PartnersBlock.styles.scss
> +            margin-bottom: f.pxToRem(60px);
here

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersBlock/PartnersBlock.styles.scss
> +        .keyPartnersBlock{
and here

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/PartnersItem/PartnersItem.styles.scss
> +        width: 100%;
mixin

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/Title/Title.styles.scss
> +            color: #891F16;
crime

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/Title/Title.styles.scss
> +                top:  f.pxToRem(-50px);
and here

2023-05-18 09:05 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/Title/Title.styles.scss
> +                right:  f.pxToRem(-80px);
here

2023-05-18 09:05 UTC, Katerix commented on src/features/AdminPage/NewsPage/Partners.styles.scss
> +    .partners-page-add-button{
pls extra line after line 9

2023-05-18 14:25 UTC, Lolimkeri commented on src/app/common/constants/api-routes.constants.ts
> +        GET: 'news/getById',
I checked other api routes and they used GET to call getById

2023-05-18 22:37 UTC, DanyilTerentiev reviewed
Please check my pr. I cleaned another's files, so there are only mine. Also cleaned all logs which saw. Waiting for your review!

2023-05-19 21:38 UTC, ormykhalyshyn approved these changes

2023-05-19 21:47 UTC, merged