Footer social media icons valerii
ita-social-projects/StreetCode_Client pull request #296
Opened 2023-05-19 10:02 UTC by ValDekh

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  Social networks in footer floated (screen in chat), 
- [ ]  Text links do not work, icons work
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-05-19 21:32 UTC, ormykhalyshyn approved these changes

2023-05-21 20:16 UTC, Katerix requested changes
Good job! Your progress is noticable. However you should consider some advice:
1. Don't use f.pxToRem() with font or line properties.
2. Please use mixins for sizes, displays and fonts
3. Be attentive to code styling and empty lines. Add them when necessary.
4. Use variables ONLY for colors
clean css is important too :)
good luck

2023-05-21 20:16 UTC, Katerix commented on src/app/layout/footer/Footer.styles.scss
> +     height: pxToRem(27px);
pls remove space (also consider using a mixin for height)

2023-05-21 20:16 UTC, Katerix commented on src/app/layout/footer/Footer.styles.scss
>      margin-right: 10%;
mixin is also good here

2023-05-21 20:16 UTC, Katerix commented on src/app/layout/footer/Footer.styles.scss
> +    align-items: center;
and here ( @include mut.flexed($align-items: center) )

2023-05-21 20:16 UTC, Katerix commented on src/app/layout/footer/Footer.styles.scss
> +        height: 20px;
=> f.pxToRem()

2023-05-21 20:16 UTC, Katerix commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +    &::before {
line 27 + 28 is equal to deleted line 26

2023-05-21 20:16 UTC, Katerix commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +      bottom: 0;
use mixins

2023-05-21 20:16 UTC, Katerix commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +      width: 100%;
same

2023-05-21 20:16 UTC, Katerix commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +    .donateInputContainerWrapper{
space before {

2023-05-21 20:16 UTC, Katerix commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
>        height: 42px;
same

2023-05-21 20:16 UTC, Katerix commented on src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.style.scss
> +  }
please use mixins and variables for COLORS

2023-05-21 20:16 UTC, Katerix commented on src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
> -
i am not sure if removing the empty line is good here

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +
a lot of empty lines

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +
pls remove line here

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +
line 25 => color variables 
line 26 => is redundant

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        font-family: 'Closer Text' !important;
use mixin

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +    justify-content:flex-end;
flex mixin here

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        font-size: f.pxToRem(14px);
no need to use rem for font size

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        line-height: f.pxToRem(18.48px);
same

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        width: 100%;
mixin

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
> +
line 14 & 17 redundant

2023-05-21 20:16 UTC, Katerix commented on src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
>      .text{
space before {

2023-05-22 09:10 UTC, ValDekh commented on src/app/layout/footer/Footer.styles.scss
> +    align-items: center;
Done

2023-05-22 09:17 UTC, ValDekh commented on src/app/layout/footer/Footer.styles.scss
> +     height: pxToRem(27px);
Done

2023-05-22 09:25 UTC, ValDekh commented on src/app/layout/footer/Footer.styles.scss
> +        height: 20px;
Done

2023-05-22 13:39 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +
Done

2023-05-22 17:31 UTC, closed without merging

2023-05-22 22:15 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        font-family: 'Closer Text' !important;
done

2023-05-22 22:20 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +
done

2023-05-22 22:24 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        width: 100%;
done

2023-05-22 22:30 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        line-height: f.pxToRem(18.48px);
done

2023-05-22 22:30 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +        font-size: f.pxToRem(14px);
done

2023-05-22 22:32 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +
done

2023-05-22 22:32 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
> +    justify-content:flex-end;
done

2023-05-22 22:33 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
>      .text{
done

2023-05-22 22:34 UTC, ValDekh commented on src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
> +
Done

2023-05-22 22:35 UTC, ValDekh commented on src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
> -
done

2023-05-22 22:42 UTC, ValDekh commented on src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.style.scss
> +  }
not my task (I didn't write this code)

2023-05-22 22:42 UTC, ValDekh commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +    &::before {
not my task (I didn't write this code)

2023-05-22 22:46 UTC, ValDekh commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +      bottom: 0;
not my task (I didn't write this code)

2023-05-22 22:46 UTC, ValDekh commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +      width: 100%;
not my task (I didn't write this code)

2023-05-22 22:46 UTC, ValDekh commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
> +    .donateInputContainerWrapper{
not my task (I didn't write this code)

2023-05-22 22:47 UTC, ValDekh commented on src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
>        height: 42px;
not my task (I didn't write this code)