finished NewsPage
ita-social-projects/StreetCode_Client pull request #325
Opened 2023-05-25 18:45 UTC by Lolimkeri

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-05-26 08:27 UTC, NadiaKishchuk requested changes

2023-05-26 08:27 UTC, NadiaKishchuk commented on src/features/AdditionalPages/NewsPage/BreadCrumb/BreadCrumb.component.tsx
> +        </Breadcrumb.Item>
please, set correct href here

2023-05-26 08:27 UTC, NadiaKishchuk commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +    newsStore.fetchNewsAll();
set it in useEffect hook

2023-05-26 08:27 UTC, NadiaKishchuk commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +    .newsContainer{
we start the mobile version from 480 if I don`t mistake

2023-05-26 09:07 UTC, Tysyatsky commented on src/app/router/Routes.tsx
> +        <Route index path="news/:id" element={<NewsPage />} />
add 'news' constant to the routes

2023-05-27 12:20 UTC, ormykhalyshyn approved these changes

2023-05-27 12:42 UTC, merged