Develop master news page
ita-social-projects/StreetCode_Client pull request #329
Opened 2023-05-27 13:32 UTC by ormykhalyshyn

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-05-28 10:58 UTC, Tysyatsky approved these changes

2023-05-28 19:10 UTC, Tysyatsky requested changes
Nothing works.

2023-06-01 07:08 UTC, NadiaKishchuk commented on src/features/AdditionalPages/NewsPage/News.component.tsx
>      var { value } = useAsync(() => NewsApi.getByUrl(newsUrl), [newsUrl]);
please, don`t use var )

2023-06-01 08:23 UTC, Lolimkeri commented on src/features/AdditionalPages/NewsPage/BreadCrumb/BreadCrumb.component.tsx
> +        </Breadcrumb.Item>
yea

2023-06-01 08:26 UTC, Lolimkeri commented on src/features/AdditionalPages/NewsPage/News.component.tsx
>      var { value } = useAsync(() => NewsApi.getByUrl(newsUrl), [newsUrl]);
done

2023-06-01 13:16 UTC, Katerix requested changes
see your progress however some fixes are requested

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +    }
dublication

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +                align-items: center;
same

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
empty line

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
+

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +        padding-top: f.pxToRem(94px);
use padding shorthand

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +            .NewsHeader {
177 - empty line

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
+

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
+

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
lots of code dublications

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +                            height: f.pxToRem(46px);
mixin here

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
line

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +                text-align: center;
mixin

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +                        }
lines 331 - 334 look super weird

2023-06-01 13:16 UTC, Katerix commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
+

2023-06-01 13:16 UTC, Katerix requested changes
see your progress however some fixes are requested

2023-06-02 18:39 UTC, LanchevychMaxym requested changes

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +    const parsedText = parse(news?.text ?? "");
Why are you setting some values as it will be undefind here?
It's better to make this as hook and set values in callbacks of that objects. In that case the value will be correct.
Untill you didn't receive all needed data from API you shouldn't display anything, you can show some Loader for users.

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +    const wrapperObj = document.querySelector('.wrapper') as HTMLElement;
What is the puspose of this wrapper?

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +    const { value } = useAsync(() => NewsApi.getByUrl(newsUrl), [newsUrl]);
What is the purpose of this component? Is it for Single news of for multiply ones?

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +                <div  className={`newsWithImageWrapper ${width > wrapperWidth * 0.6 ? 'Full' : ''}`}>
This will not be updated if other components rerendered, please, pay attention to that

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +                    <Link className={`Link ${typeof newsArr[newsIndex - 1]?.url === 'undefined' ? 'toHide' : ''}`}
For this reason you don't need to return all the news from the backend. You can handle this issue there. I mean you can create new API that will return you this single News and IDs(or any other parameter you need) of the next and previous ones, so you can simplify everything.

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +                    <Link className={`Link ${typeof newsArr[newsIndex + 1]?.url === 'undefined' ? 'toHide' : ''}`}
You shouldn't handle this showing or hiding like this. You should load info about your news and then render this. So while you're loading you can either display loader on the page or don't show anything (it's a question to PO)

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +        [],
As I mentioned, it's better not to fetch all records here, you can simplify it

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +    };
Can't we replace it with just one hook?

2023-06-02 18:39 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +                                <Link className={`Link ${news?.url === getNewsElement(newsArr, newsIndex)?.url ? 'toHide' : ''}`} to={`/news/${getNewsElement(newsArr, newsIndex)?.url}`} >
As I mentioned before, you shouldn't handle such cases with classes

2023-06-02 19:26 UTC, Lolimkeri commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +    const { value } = useAsync(() => NewsApi.getByUrl(newsUrl), [newsUrl]);
single news

2023-06-03 11:44 UTC, Lolimkeri commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +                        }
it should be ok

2023-06-03 11:46 UTC, Lolimkeri commented on src/features/AdditionalPages/NewsPage/News.styles.scss
> +
deleted these bcs they dont have any means rn

2023-06-07 11:22 UTC, LanchevychMaxym commented on src/features/AdditionalPages/NewsPage/News.component.tsx
> +    const paragraphCount = (pppppText?.match(/<p\b[^>]*>/gi) || []).length;
Let's remove these as we discussed

2023-06-07 11:43 UTC, LanchevychMaxym approved these changes

2023-06-14 17:09 UTC, Tysyatsky commented
Checked the code and how it works, found new bug with the page. If the text is small enough, the page looks like below. Linking is okay and page looks great in other cases. 
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/77460353/1ac9acc0-a621-4bc3-89c5-1f50e13fca3e)

2023-06-14 17:11 UTC, Tysyatsky reviewed
Checked the code and how it works, found new bug with the page. If the text is small enough, the page looks like below. Linking is okay and page looks great in other cases.
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/77460353/cd36d473-5c5d-4442-968b-ec018779fdd8)

2023-06-14 17:16 UTC, Tysyatsky approved these changes
After the discussion about the photo orientation, the last comment was recorded, but fixing is delayed for the future updates.

2023-06-14 23:41 UTC, merged