Adaptive for banner and partners
ita-social-projects/StreetCode_Client pull request #383
Opened 2023-06-16 11:17 UTC by vvbogdanovih

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-16 11:29 UTC, NadiaKishchuk requested changes

2023-06-16 11:29 UTC, NadiaKishchuk commented on src/features/MainPage/StaticBanners/StaticBanner.styles.scss
> +                    line-height: 16.41px;
you have a lot of duplicated styles in different screen extensions, please fix it

2023-06-16 22:37 UTC, vvbogdanovih commented on src/features/MainPage/StaticBanners/StaticBanner.styles.scss
> +                    line-height: 16.41px;
Removed styles that are repeated and do not affect the display of the page

2023-06-17 20:57 UTC, MaksBrat requested changes

2023-06-17 20:57 UTC, MaksBrat commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +
pls remove the blank line

2023-06-17 20:57 UTC, MaksBrat commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +
same)

2023-06-17 20:57 UTC, MaksBrat commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +
here and in the following blocks as well

2023-06-18 10:50 UTC, vvbogdanovih commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +
Removed blank lines

2023-06-18 11:28 UTC, MaksBrat commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +                @include mut.rem-margined($top: 15px, $right: 12px, $bottom: 15px, $left: 12px);
duplication 67 and 78 lines

2023-06-18 11:28 UTC, MaksBrat commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +                @include mut.rem-margined($top: 20px, $right: 15px, $bottom: 20px, $left: 15px);
duplication 45 and 56 lines

2023-06-19 08:09 UTC, vvbogdanovih commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +                @include mut.rem-margined($top: 20px, $right: 15px, $bottom: 20px, $left: 15px);
Removed duplicates in PartnersBlockMain.styles

2023-06-19 10:51 UTC, MaksBrat approved these changes

2023-06-27 11:52 UTC, NadiaKishchuk commented on src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss
> +    }
I think it is better to use margin auto for left and right if possible.  So you must create the wrapper div and the element must be inside. it looks like it is now in the same way.

2023-06-27 11:52 UTC, NadiaKishchuk commented on src/features/MainPage/StaticBanners/StaticBanner.styles.scss
> +            .mainContainer {
in your component, you don`t have the catalog class used.  So why it is here?

2023-06-28 13:05 UTC, Dobriyr requested changes
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/67451349/86d52345-f276-4cd5-b7e4-62059e08dfcc)
Cutting border-radius when screen width  lover then 350px
it seems to me that in the styles you should change the width to 100% instead of fixed
---
There is also no box-shadow
Your button
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/67451349/df2382c1-da6b-400a-9ae8-ac5e31f30174)

button on Figma
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/67451349/3c4598b5-ad5c-41a2-9b9a-13842cf18b2b)

2023-06-29 11:06 UTC, NadiaKishchuk approved these changes

2023-06-29 12:37 UTC, KateYatsiuk approved these changes

2023-07-03 12:44 UTC, Dobriyr approved these changes

2023-07-03 12:47 UTC, merged