created adaptives for team, streedcode sliders
ita-social-projects/StreetCode_Client pull request #406
Opened 2023-06-21 14:25 UTC by FlSlaves

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

Lack of adaptives for mobile, tablet

## Summary of change

Added adaptives for tablet and mobile.

## Testing approach

--

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-21 15:07 UTC, MaksBrat approved these changes

2023-06-21 15:07 UTC, MaksBrat commented on src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
> +        @media screen and (max-width: 767px){
use pxToRem()

2023-06-21 15:09 UTC, MaksBrat commented on src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
> +
remove blank line

2023-06-21 15:13 UTC, MaksBrat commented
overrall, please check your code and fix indentations, remove blank likes and use pxToRem()

2023-06-21 16:11 UTC, NadiaKishchuk requested changes

2023-06-21 16:11 UTC, NadiaKishchuk commented on src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
> +                border-bottom: 0px !important;
please, don't use important if it is not except the critical situation

2023-06-21 16:11 UTC, NadiaKishchuk commented on src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
> +                    text-align: center;
use our mixin flexed instead

2023-06-21 16:11 UTC, NadiaKishchuk commented on src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
>          color: #1D1F23;
don't use the color here as a string, it is better to set it as scss variable and use it then.

2023-06-21 16:11 UTC, NadiaKishchuk commented on src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
> +        @media screen and (max-width: 767px){
the same here, don't use color string in the styles and don't use px, use the pxToRem function

2023-06-26 15:07 UTC, MaksBrat approved these changes

2023-06-27 18:12 UTC, KateYatsiuk commented
Please, fill in the pull request details correctly. Why are the sections "Assignees", "Project", "Development" empty?

2023-07-06 17:22 UTC, KateYatsiuk approved these changes

2023-07-10 12:17 UTC, Dobriyr requested changes
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/67451349/9cd109c1-f417-498e-b10e-389bf34ec93e)
The text should be centered vertically
Tablet version

---
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/67451349/75e53b66-c0ff-4bdc-b9d2-5e1697c65804)
unnecessary side indentation
Tablet version

---

![image](https://github.com/ita-social-projects/StreetCode_Client/assets/67451349/702921ac-7784-4aae-a79b-3b78d365e4d5)
It is worth adding a restriction to show no more than 3 slides
Tablet version

2023-07-26 18:57 UTC, closed without merging