Fixed 'Copy check' button and added a copy message
ita-social-projects/StreetCode_Client pull request #408
Opened 2023-06-21 18:38 UTC by vvbogdanovih

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-21 19:43 UTC, MaksBrat requested changes

2023-06-21 19:43 UTC, MaksBrat commented on src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
> +    const handleCopy1 = () => {
it would be better to name smth like "handleAfterCopy"

2023-06-21 19:43 UTC, MaksBrat commented on src/features/AdditionalPages/SupportUsPage/SupportUs.styles.scss
> +    left: 20px;
use pxToRem

2023-06-21 19:52 UTC, vvbogdanovih commented on src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx
> +    const handleCopy1 = () => {
Thanks, I forgot to rename it

2023-06-21 19:52 UTC, vvbogdanovih commented on src/features/AdditionalPages/SupportUsPage/SupportUs.styles.scss
> +    left: 20px;
Done

2023-06-21 21:02 UTC, MaksBrat approved these changes

2023-06-28 12:43 UTC, KateYatsiuk approved these changes

2023-07-03 12:35 UTC, Dobriyr approved these changes

2023-07-03 12:37 UTC, merged