AR button fix
ita-social-projects/StreetCode_Client pull request #434
Opened 2023-07-03 10:19 UTC by vvbogdanovih

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-07-03 13:37 UTC, MaksBrat approved these changes

2023-07-03 14:13 UTC, OlehHatsko commented on src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
> +            TransactionLinksApi.getById(id).then((x: any) => {
Look at line 66. Try to write code in same convention every time

2023-07-03 14:17 UTC, OlehHatsko requested changes
fix comments

2023-07-04 13:41 UTC, vvbogdanovih commented on src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
> +            TransactionLinksApi.getById(id).then((x: any) => {
Done

2023-07-04 17:28 UTC, merged