Feature modals change
ita-social-projects/StreetCode_Client pull request #580
Opened 2023-08-02 09:22 UTC by FlSlaves

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

Reseting fields for modal windows when closing by close button, when pressing not on the zone of modal data is saving on modal. Also changed youtube link on main page

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-08-04 10:59 UTC, maximu211 approved these changes

2023-08-04 13:15 UTC, maximu211 requested changes
on wow fact after clicking on "X" photo still in modal window

2023-08-07 15:07 UTC, maximu211 approved these changes

2023-08-07 15:45 UTC, MementoMorj approved these changes

2023-08-07 15:45 UTC, merged