Feat/streetcode art gallery
ita-social-projects/StreetCode_Client pull request #64
Opened 2023-01-24 13:57 UTC by Tatiana2424

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-01-24 14:04 UTC, EyR1oN approved these changes

2023-01-24 18:35 UTC, dimasster approved these changes

2023-01-25 11:01 UTC, AleXLaeR requested changes

2023-01-25 11:01 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGallery.styles.scss
> +    height: 560px !important;
- I don't think you need the `!important` p-ty here.
- Height must be converted to **rem** units

2023-01-25 11:39 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
> +    streetcodeArtStore;
done

2023-01-25 11:44 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
> +      async ({ art: { description, image }, index }) => {
done

2023-01-25 11:46 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
> +  );
done

2023-01-25 11:50 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
> +              rows={1}
done

2023-01-25 12:01 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.styles.scss
>  }
done

2023-01-25 12:03 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGallery.styles.scss
> +    height: 560px !important;
done

2023-01-25 12:08 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
>    flex: 1 1 80px;
done

2023-01-25 12:10 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +const ArtGalleryListOfItem = (artGallery: ArtGallery) => {
done

2023-01-25 12:48 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
> +  }
done

2023-01-25 13:25 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
> +  font-size: 15px;
done

2023-01-25 14:07 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +  for (let i: number = 0; i < artGallery.images.length; i++) {
done

2023-01-25 14:07 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +  titles: string[];
done

2023-01-25 14:08 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.component.tsx
> +        <div className={`img_data img_data-${description==undefined && title==undefined ? "empty" : "full"}`}>
done

2023-01-25 14:08 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +        title={artGallery.titles[i]}
done

2023-01-25 15:13 UTC, AleXLaeR requested changes

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
>  }
You are not utilizing the main SASS feature - selector nesting

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
> +  @include mut.with-font;
It is a bad practice to include mixing in a non-functiona lstyle (w/o parentheses).

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +const ArtGalleryListOfItem = ({artGalleryList}:ArtGalleryData) => {
Naming issue is still present, even though it has been marked resolved

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +interface ArtGalleryData {
Here I advised you to memoize prop values, because they won't be changing often. To no avail, however.

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.styles.scss
> +  width: pxToRem(1210px);
These classes should be encapslated in a container which uses them.

2023-01-25 15:13 UTC, AleXLaeR commented on src/models/media/art.model.ts
> +export interface IndexedArt {
Spacing.

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.styles.scss
> +  @include mut.flex-centered;
It is a bad practice to include mixing in a non-functiona lstyle (w/o parentheses).

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +import { IndexedArt } from "@/models/media/art.model";
Extra slash '/' between `@` and `models...` in a path construction.

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
>    opacity: 0;
I think we need an opacity-based transition here.

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.component.tsx
> +const ArtGalleryItem = ({ artGalleryItem }: Props) => {
It is a good practice to destructure the prop-values at a definition level.

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.component.tsx
> +import { IndexedArt } from "@/models/media/art.model";
Extra slash '/' between `@` and `models...` in a path construction.

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
>      if (offsetSumForSlide != SECTION_AMOUNT) {
It would be better to split the complex logic into separate functions - component- or file-based.

2023-01-25 15:13 UTC, AleXLaeR commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
>  const ArtGallery = () => {
Most of the components are named as `<smth>Block`.

2023-01-25 15:45 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
>  .img_data {
done

2023-01-25 15:45 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
> +  @include mut.set-positioning($top: "auto", $right: "auto", $bottom: 0, $left: "auto");
done

2023-01-25 15:46 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
>  }
done

2023-01-25 15:47 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
> +  @include mut.with-font;
done

2023-01-25 15:49 UTC, Tatiana2424 commented on src/models/media/art.model.ts
> +export interface IndexedArt {
done

2023-01-25 15:49 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.styles.scss
> +  @include mut.flex-centered;
done

2023-01-25 15:50 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +import { IndexedArt } from "@/models/media/art.model";
done

2023-01-25 15:54 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
>    opacity: 0;
done

2023-01-25 15:55 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.component.tsx
> +import { IndexedArt } from "@/models/media/art.model";
done

2023-01-25 16:14 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
> +  flex: pxToRem(80px);
![image](https://user-images.githubusercontent.com/92846322/214616259-79b6d833-0a5b-4a22-936a-3a700897a57c.png)

2023-01-25 16:28 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGallery.component.tsx
>  const ArtGallery = () => {
done

2023-01-25 16:29 UTC, PingvinAustr approved these changes

2023-01-25 16:33 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.component.tsx
> +const ArtGalleryItem = ({ artGalleryItem }: Props) => {
done

2023-01-25 16:38 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
> +  color: c.$pure-white-color;
done

2023-01-25 16:40 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.styles.scss
> +  flex: pxToRem(80px);
Without flex: pxToRem(80px), the result will be this

2023-01-25 16:40 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.component.tsx
> +interface ArtGalleryData {
done

2023-01-25 16:45 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryItem/ArtGalleryItem.component.tsx
> +const ArtGalleryItem = ({ artGalleryItem }: Props) => {
done

2023-01-25 17:32 UTC, Tatiana2424 commented on src/features/StreetcodePage/ArtGallery/ArtGalleryListOfItem/ArtGalleryListOfItem.styles.scss
> +  width: pxToRem(1210px);
done

2023-01-25 17:59 UTC, AleXLaeR approved these changes

2023-01-25 18:01 UTC, merged