Fix/partners
ita-social-projects/StreetCode_Client pull request #69
Opened 2023-01-28 22:28 UTC by dimasster

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-01-28 22:47 UTC, EyR1oN approved these changes

2023-01-29 08:40 UTC, AleXLaeR requested changes

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.content.tsx
>                      {partner.partnerSourceLinks.map((sl) => (
`sl` parameter may be destructured to reduce boilerplate and increase readability.

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerItem.styles.scss
>          transition: all .5ms ease;
- `transition` prop-ty should be vendored for cross-browser support.
- Also, a half of a millisecond? Is that even perceivable by a human eye?

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.content.tsx
>      const { getImage } = imagesStore;
These two declarations may be inlined.

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.content.tsx
>  import Partner from '@/models/partners/partners.model';
Redundant slash between `@` and `models`.

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.content.tsx
>      partner: Partner
Inconsistent style; no trailing semicolon.

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.content.tsx
>                      style={{ display: partner.partnerSourceLinks.length < 1 ? 'none' : '' }}
`display` p-ty cannot be equal to an empty string.  The default disaplay of (almost) every html-tag is `block`.

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.content.tsx
> +const PartnerContent = ({ partner }: Props) => {
`partner` prop may be destructured.

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.styles.scss
> +        line-height: pxToRem(26.4px);
`-line-height` p-ty shouldn't be set in **rems**.
Refer to: https://stackoverflow.com/questions/15132671/ems-for-line-height.
![image](https://user-images.githubusercontent.com/99609396/215315068-8fba63d4-df0d-4c7c-9487-53da3a507ec7.png)

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.styles.scss
> +        @include mut.with-font($font-family: f.$closer-text-font, $font-size: 20px, $font-weight: 500);
`font-size` is 20px by default.

2023-01-29 08:40 UTC, AleXLaeR commented on src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.styles.scss
> +        @include mut.with-font($font-size: 20px, $font-weight: 300);
Same as above.

2023-01-29 18:01 UTC, Tatiana2424 approved these changes

2023-01-29 18:01 UTC, merged

2023-01-29 18:01 UTC, AleXLaeR approved these changes