add possibility to redirect to news with click
ita-social-projects/StreetCode_Client pull request #907
Opened 2023-10-09 16:33 UTC by Adeodonne

dev
## Description
add possibility to redirect to news with click

## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-10-11 19:18 UTC, BohdanBybliv approved these changes

2023-10-12 18:18 UTC, Oleh-Kril requested changes

2023-10-12 18:18 UTC, Oleh-Kril commented on src/features/MainPage/NewsSlider/NewsSlider.component.tsx
> +    const [coordinatesOnMouseDown, setCoordinatesOnMouseDown] = useState([0, 0]);
please try to rewrite it using just one state [dragging, setDragging] to make it more clear

2023-10-13 17:20 UTC, MementoMorj approved these changes

2023-10-13 17:20 UTC, merged