generic pagination + getting streetcodes on main page with pagination/front
ita-social-projects/StreetCode_Client pull request #911
Opened 2023-10-10 15:19 UTC by malyna2

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-10-12 19:08 UTC, Oleh-Kril requested changes
Weird behaviour with requests (I changed pageSize to 1 when was testing)
<img width="763" alt="Screenshot 2023-10-12 at 10 04 52 PM" src="https://github.com/ita-social-projects/StreetCode_Client
<img width="821" alt="Screenshot 2023-10-12 at 10 06 35 PM" src="https://github.com/ita-social-projects/StreetCode_Client/assets/91199925/e9f4a670-d794-47d1-85df-713d29cae03d">
/assets/91199925/c8e02e31-3dac-4d4e-8732-2329b56f0671">
<img width="814" alt="Screenshot 2023-10-12 at 10 06 24 PM" src="https://github.com/ita-social-projects/StreetCode_Client/assets/91199925/f57c402e-1d11-49f7-b1f0-81a6f490c24d">

2023-10-15 12:10 UTC, malyna2 commented on src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx
> +                    await ImagesApi.getById(streetcode.imageId)
Solved this problem. await was needed to make sure we recieved all images before setting to useState

2023-10-15 12:12 UTC, malyna2 commented
Issue with loading of all streetcodes can be reproduced only with strict mode

2023-10-28 16:27 UTC, Oleh-Kril approved these changes
Good job

2023-10-28 16:27 UTC, Oleh-Kril commented on src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx
> +                        pomises.push(ImagesApi.getById(newStreetcodes[i].imageId).then((img) => {
typo

2023-10-28 20:23 UTC, merged