fix problem with text, that isn't showed in text and authorship on admin page and two small fixes
ita-social-projects/StreetCode_Client pull request #927
Opened 2023-10-16 18:51 UTC by BohdanBybliv

1. Fixed problem with text, that isn't showed in text and authorship on admin page:
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/125794488/d56d98c8-6c1d-493b-9bd3-aabb60d032f1)

2. Made the same style for all slider buttons:
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/125794488/da905275-29f0-49c9-b560-8d01e67d68cc)

3. If one news is displayed, add posibility to open news with click.

2023-10-18 10:58 UTC, Maxym1507 requested changes
1. Authorship on admin page is still empty after editing.
2. Broken functionality of creating a streetcode. There no fields "Заголовок", "Основний текст", "Авторство"

2023-10-18 17:48 UTC, Maxym1507 approved these changes

2023-10-19 21:21 UTC, mykola-krai approved these changes

2023-10-22 10:39 UTC, KateYatsiuk approved these changes

2023-10-30 20:34 UTC, MementoMorj approved these changes

2023-10-30 20:34 UTC, merged