add caption to the streetcode catalog page
ita-social-projects/StreetCode_Client pull request #931
Opened 2023-10-17 17:37 UTC by BohdanBybliv

**Added "Стріткоди" caption on the streetcode catalog page in right upper corner.**
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/125794488/e241f064-9a4b-43ae-9660-b260ef72a03e)
on mobile:
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/125794488/f581ec52-4748-4d1d-98d4-500dcc82ffcd)

2023-10-18 07:20 UTC, Maxym1507 approved these changes

2023-10-19 20:29 UTC, mykola-krai requested changes
If an element styles are stated outside the media rules, they work for each media rule.
So they should not be duplicated, unless necessarily or they must be changed.

2023-10-19 20:29 UTC, mykola-krai commented on src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
> +
Duplicate for:
lines 30-38.

2023-10-19 20:29 UTC, mykola-krai commented on src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
> +            width: 100%;
Duplicate for:
line 28 width: 100%;

2023-10-19 20:29 UTC, mykola-krai commented on src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
> +            margin-top: pxToRem(20px);
Check margins for mobile and tablet version in figma.

2023-10-20 16:10 UTC, BohdanBybliv commented on src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
> +            margin-top: pxToRem(20px);
I fixed it

2023-10-22 10:35 UTC, KateYatsiuk commented on src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
> +    color: #891F16;
Consider using variables for colors, we have an appropriate file for them

2023-10-22 10:36 UTC, KateYatsiuk approved these changes
Please, pay attention to my comment

2023-10-23 18:47 UTC, mykola-krai approved these changes

2023-10-30 20:44 UTC, merged