Update search
ita-social-projects/StreetCode_Client pull request #932
Opened 2023-10-18 14:45 UTC by BohdanBybliv

Added utility function and use it on components, made code clean

2023-10-19 22:00 UTC, mykola-krai reviewed
What is the expected behavior when searching for phrase in streetcode text block..
..from another page?
..from same (streeеcode) page? (Now, it performs double scrolling)

2023-10-22 10:27 UTC, KateYatsiuk requested changes
It seems to me that smth wrong is going on with search. **Contact me if don't get it, I cannot attach video.**
_**EXAMPLE:**_ 
1. Search for "Роман був" on main page:
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/9eb93fbd-e4cc-4879-a9c1-505ae1aed12d)
**Result** (redirected -> OK, but scrolled to the main text -> I believe it's wrong behaviour):
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/af5b8685-893a-4fe7-af1f-5b03fd57bba8)

2. On main page scroll down a little (for example to the news block) and search for "Роман був" again:
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/5338eb56-5c01-4289-8669-6c6fee2227d0)
**Result** -> nothing happens, no redirect.

2023-10-30 20:51 UTC, MementoMorj approved these changes

2023-10-30 20:51 UTC, malyna2 approved these changes

2023-10-30 20:51 UTC, merged