Burger menu slider dot fix
ita-social-projects/StreetCode_Client pull request #940
Opened 2023-10-20 12:30 UTC by AndriiS1

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-10-21 08:21 UTC, KateYatsiuk requested changes
It seems that there are still problems:
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/23ba291c-e81a-46cb-a43d-40db7511899d)
![image](https://github.com/ita-social-projects/StreetCode_Client/assets/113370393/b66da531-e002-4c8d-9c13-0dbe3672e37b)
The same problem is on desktop. I'd be grateful if you could fix it as well

2023-10-22 16:15 UTC, AndriiS1 commented
> It seems that there are still problems: ![image](https://user-images.githubusercontent.com/113370393/277096593-23ba291c-e81a-46cb-a43d-40db7511899d.png) ![image](https://user-images.githubusercontent.com/113370393/277096600-b66da531-e002-4c8d-9c13-0dbe3672e37b.png) The same problem is on desktop. I'd be grateful if you could fix it as well

Thank you. Try it now

2023-10-22 17:19 UTC, KateYatsiuk approved these changes

2023-10-25 14:59 UTC, FlSlaves approved these changes

2023-10-30 21:00 UTC, MementoMorj approved these changes

2023-10-30 21:00 UTC, merged