Fix the search dropdown
ita-social-projects/StreetCode_Client pull request #989
Opened 2023-11-08 21:48 UTC by BohdanBybliv

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-11-10 10:39 UTC, Oleh-Kril requested changes
Good job, now it works and looks better.

Please fix my comments of code style and fix a bug on mobile:
when I as a user tap a search button and write smth in the input and press enter mobile button then nothing happens also with enter button on desktop

2023-11-10 10:39 UTC, Oleh-Kril commented on src/app/layout/header/HeaderBlock.component.tsx
>      const [searchQuery, setSearchQuery] = useState<string>('');
I would suggest to use alias for off function or refactor useToggle because it's not obvious what this function does from name

2023-11-10 10:39 UTC, Oleh-Kril commented on src/app/layout/header/HeaderBlock.component.tsx
> +    useOnClickOutside(inputRef, searchBlockRef, onDimCancel);
If you need to pass multiple components in hook then it's better to use array because what will you do if you need to pass 3 components in another use case of this hook ? Consider refactoring this hook to use array of Ref objects and a handler

2023-11-10 10:39 UTC, Oleh-Kril commented on src/app/layout/header/HeaderBlock.component.tsx
> +                                        hiddenHeaderInput ${((isInputActive && isHeaderHidden && windowSize.width > 1024) ? 'active' : '')}`}
it's better to use useMediaQuery hook instead of windowSize.width

2023-11-10 10:39 UTC, Oleh-Kril commented on src/app/layout/header/HeaderBlock.component.tsx
> +                    {windowSize.width > 1024 && <HeaderSkeleton />}
it's better to use useMediaQuery hook instead of windowSize.width

2023-11-10 10:39 UTC, Oleh-Kril commented on src/app/layout/header/HeaderBlock.component.tsx
> +                <Popover
Code duplication. Please decouple components to reuse them and consider storing props of popover in object and restructuring it in <Popover /> component. In this case you will only need to provide additional props such as arrow={false} and others for mobile and don't duplicate shared props of popover on desktop and mobile

2023-11-10 10:39 UTC, Oleh-Kril commented on src/app/layout/header/HeaderBlock.styles.scss
> +    padding: $search-popover-padding;
we use rem. Wrap this value with f.pxToRem() scss function

2023-11-15 18:35 UTC, ValDekh approved these changes

2023-11-17 10:51 UTC, FlSlaves approved these changes

2023-11-18 21:01 UTC, merged